apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm-config
data:
  morpho-realm.json: |    
    {
        "realm": "morpho",
        "enabled": true,
        "displayName": "Morpho Development Realm",
        "sslRequired": "none",
        "registrationAllowed": true,
        "loginWithEmailAllowed": true,
        "duplicateEmailsAllowed": false,
        "resetPasswordAllowed": true,
        "editUsernameAllowed": false,
        "clients": [
            {
                "clientId": "morpho-client",
                "enabled": true,
                "protocol": "openid-connect",
                "publicClient": true,
                "directAccessGrantsEnabled": true,
                "standardFlowEnabled": true,
                "fullScopeAllowed": true,
                "redirectUris": [
                    "*"
                ],
                "webOrigins": [
                    "*"
                ]
            }
        ],
        "users": [
            {
                "username": "testuser",
                "enabled": true,
                "emailVerified": true,
                "firstName": "Test",
                "lastName": "User",
                "email": "testuser@example.com",
                "requiredActions": [
                ],
                "credentials": [
                    {
                        "type": "password",
                        "value": "password123",
                        "temporary": false
                    }
                ]
            }
        ]
    }