apiVersion: apps/v1
kind: Deployment
metadata:
  name: morpho-proxy
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: morpho-proxy
  template:
    metadata:
      labels:
        app: morpho-proxy
    spec:
      enableServiceLinks: false 
      initContainers:
      - name: wait-for-deps
        image: {{ .Values.images.busybox }}
        command: ['sh', '-c', 'until nc -z redis {{ .Values.ports.redis }} && nc -z kafka {{ .Values.ports.kafka }}; do echo waiting for dependencies; sleep 3; done;']
      containers:
      - name: morpho-proxy
        image: {{ .Values.images.proxy }}
        imagePullPolicy: Never
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "{{ .Values.ports.redis }}"
        - name: KAFKA_BROKERS
          value: "kafka:{{ .Values.ports.kafka }}"
        - name: OIDC_ISSUER_URI
          value: "http://{{ .Values.global.externalDomain }}:{{ .Values.nodePorts.keycloak }}/realms/morpho"
        - name: CANARY_PERCENTAGE
          value: "{{ .Values.config.canaryPercentage }}"
        - name: LEGACY_URI
          value: "http://legacy-monolith:{{ .Values.ports.backendService }}"
        - name: MODERN_URI
          value: "http://modern-microservice:{{ .Values.ports.backendService }}"
        - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_GATEWAY
          value: DEBUG
        - name: ROUTE_PATH
          value: "/api"
---
apiVersion: v1
kind: Service
metadata:
  name: morpho-proxy
spec:
  type: NodePort
  selector:
    app: morpho-proxy
  ports:
  - port: {{ .Values.ports.proxy }}
    targetPort: {{ .Values.ports.proxy }}
    nodePort: {{ .Values.nodePorts.proxy }}